// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzqqf3-DI8u6T-ioFgoVlPDjTFoHlDa58',
    appId: '1:847217202068:web:b5d788c982bd47a0447581',
    messagingSenderId: '847217202068',
    projectId: 'fir-storage-fe884',
    authDomain: 'fir-storage-fe884.firebaseapp.com',
    databaseURL: 'https://fir-storage-fe884-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storage-fe884.appspot.com',
    measurementId: 'G-TKGHX2DZBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHIDsvP9r5QmeYEhdRmn2oIRBvkwcgDc',
    appId: '1:847217202068:android:657b53bfaaa1d84c447581',
    messagingSenderId: '847217202068',
    projectId: 'fir-storage-fe884',
    databaseURL: 'https://fir-storage-fe884-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storage-fe884.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMeZPIopBUCrOWlNCyDYt7EgjGOSY0Rc',
    appId: '1:847217202068:ios:11ef88238b9e0773447581',
    messagingSenderId: '847217202068',
    projectId: 'fir-storage-fe884',
    databaseURL: 'https://fir-storage-fe884-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storage-fe884.appspot.com',
    iosBundleId: 'com.example.firebaseStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMeZPIopBUCrOWlNCyDYt7EgjGOSY0Rc',
    appId: '1:847217202068:ios:4098103863c997f1447581',
    messagingSenderId: '847217202068',
    projectId: 'fir-storage-fe884',
    databaseURL: 'https://fir-storage-fe884-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-storage-fe884.appspot.com',
    iosBundleId: 'com.example.firebaseStorage.RunnerTests',
  );
}
